### ISSUE TITLE
Can't run using yarn

### ISSUE THREAD

**Issue by mccraveiro** [bufferapp/ui#20]
Hi! 

I've tried to run the project using yarn but it raises the following error: 
```sh
Failed to compile.

./src/index.jsx
Error: Cannot find module '@babel/preset-react'
```

What I've done was just: 
```sh
$ yarn
$ yarn run start
```

Then I began to investigate this error and it seems to be an issue with this line on package.json:
https://github.com/bufferapp/ui/blob/0576c56d28fe4254e59dfb3cfa39479d4d378f86/package.json#L176

It states that we are using the `@babel/preset-react` package but we don't explicitly declare it on package.json. Instead, we are using `babel-preset-react-app` that requires that we use `react-app` as the babel preset. 

This bug seems to have been introduced on this commit:
https://github.com/bufferapp/ui/commit/f15c9af255eaeab3e03f112db1b125521b77ede6 

However, I don't know why the project runs fine when using NPM. My guess is that it is declared on package-lock.json. 

What should we do? 

1. Declare `@babel/preset-react` on package.json? 
2. Replace the babel preset again?

**Comment by ivanaszuber** [comment]
Yikes, sorry for the troubles there @mccraveiro 😬 , and thanks for letting us know! I'll take a look at that one asap 👍

**Comment by hamstu** [comment]
Closing as this project is meant to be used with `npm` right now.
