### ISSUE TITLE
SVG icon Clock

### ISSUE THREAD

**Issue by flexbox** [bufferapp/ui#23]
The clock icon is trimmed on right. I think the icon is not centered in the viewbox.
https://bufferapp.github.io/ui/#/ui/ui/icon

Tested on Firefox without retina display

![image](https://user-images.githubusercontent.com/360936/50216434-a70db700-037d-11e9-8f7d-157fff535723.png)

**Comment by ivanaszuber** [comment]
Heya @flexbox thanks so much for reporting this issue 🙇 ! Yup, we're aware of some styling issues with the Icons. We are still very much in the early stages of this project and hope to get that all polished up super soon!
I'll let you know as soon as those are fixed and ready to be used 🙌

**Comment by hamstu** [comment]
This is fixed now. :)
