### ISSUE TITLE
Move AppShell away from @bufferapp/ui

### ISSUE THREAD

**Issue by msanroman** [bufferapp/ui#235]
**What**

- [x] Copy the AppShell from bufferapp/ui into a new repo
- [x] For backwards compatibility: allow for several @bufferapp/ui versions to still export the AppShell, but make it by importing the one in the new repo. **Add a warning so that engineers know this is deprecated and that they should use the new flow.**

**Why**
- UI libraries are as context agnostic as possible, which is not the case of the AppShell component.
- Most of the recent work on the AppShell had nothing to do with UI changes (add logic props, remove or add support for Buffer products)

**Comment by hamstu** [comment]
Done here: https://github.com/bufferapp/app-shell

Still need to add deprecation notice to `@bufferapp/ui`
