### ISSUE TITLE
Simplify app pathnames

### ISSUE THREAD

**Issue by anafilipadealmeida** [bufferapp/ui#238]
**What**
Simplify pathnames in the ui documentation app (https://github.com/bufferapp/ui/tree/master/src/documentation/app)

**Why**
The pathnames are currently not very intuitive

**Examples:**
<img width="822" alt="Screenshot 2020-09-29 at 12 19 49" src="https://user-images.githubusercontent.com/16758464/94552198-68917580-024e-11eb-997d-d4788ec95731.png">
<img width="754" alt="Screenshot 2020-09-29 at 12 20 01" src="https://user-images.githubusercontent.com/16758464/94552242-79da8200-024e-11eb-8a80-682c64a4ecf7.png">

**Comment by ssvmvss** [comment]
PR: https://github.com/bufferapp/ui/pull/252

**Comment by ssvmvss** [comment]
Closing this one since we've decided to move all UI library documentation to Notion / Storybook. Improving the current pathnames does not make sense anymore.
