### ISSUE TITLE
Show more relevant search results first

### ISSUE THREAD

**Issue by anafilipadealmeida** [bufferapp/ui#242]
**What**
Currently, when we insert something in the search input, we get a list of results ordered by first item containing the searched expression:
<img width="227" alt="Screenshot 2020-10-12 at 23 18 05" src="https://user-images.githubusercontent.com/16758464/95857697-e6c44080-0d53-11eb-91bf-a7779357f333.png">
We want to **display first the results that start with** the searched expression, and only after show the other results that contain the searched expression. In this case, typing "P" would show first "Pending".

**Why**
Users want to see the most relevant info. When users do a basic search by “Po” they expect the first result to be Portland and the second to be Minneapolis and not the opposite. (unless we had a more sophisticated search that perhaps was listing last searches made by that user first, which is not the case)

**Comment by mickmahady** [comment]
Deployed with https://github.com/bufferapp/ui/pull/257
