### ISSUE TITLE
Change default branch to "main"

### ISSUE THREAD

**Issue by msanroman** [bufferapp/ui#244]
https://github.com/github/renaming

**Comment by billfienberg** [comment]
It looks like this is done. 

<img width="1552" alt="buffer-ui-main-branch" src="https://user-images.githubusercontent.com/6130520/106664173-501dc880-656a-11eb-8dbe-ccdeaa4a6179.png">

Can this issue be closed?

**Comment by hamstu** [comment]
Thanks @billfienberg. You're correct, closing this one now. 💯
