### ISSUE TITLE
Make form elements style consistent

### ISSUE THREAD

**Issue by anafilipadealmeida** [bufferapp/ui#256]
**What**
Our Input and TextArea components don't have the same border color and placeholder color.
![Screenshot 2020-10-28 at 14 27 00](https://user-images.githubusercontent.com/16758464/97449515-a9ea7300-1929-11eb-8960-ba1dae86901b.png)
![Screenshot 2020-10-28 at 14 26 52](https://user-images.githubusercontent.com/16758464/97449553-b2db4480-1929-11eb-9a3b-0fd50e33ac8f.png)
**Why**
When using both elements in a form, it will look weird to have them with different styles.

**Comment by anafilipadealmeida** [comment]
@letsbleachthis, any thoughts on this? What would be the ideal styles?

**Comment by gmzjuliana** [comment]
hey @anafilipadealmeida just confirmed, placeholder text does need to meet contrast ratio guidelines, in this case: `WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text`

**Comment by letsbleachthis** [comment]
> @letsbleachthis, any thoughts on this? What would be the ideal styles?

Hey @anafilipadealmeida — good catch, I believe the border color for both components should be Gray.

I've wondered about the placeholders as well, they do feel quite light. Let's try using Dark Gray (#636363) instead. I worry that it might look almost indistinguishable from a user's entered text in Darker Gray, but it's important to make these elements accessible.
