### ISSUE TITLE
Button looks cut on the left side when is disabled

### ISSUE THREAD

**Issue by MayaUribe** [bufferapp/ui#270]
The Button component looks like it's cut on the left side of the button when it's disabled.

<img src="https://user-images.githubusercontent.com/988972/101355376-c49ff800-3896-11eb-8273-c618e0132671.jpg" width="400px" />

This bug seems to be related to this commit: https://github.com/bufferapp/ui/commit/0bbc740a728603d5bbc1199689f35d982681d0c9

**Comment by hijuliancode** [comment]
Hi @MayaUribe , here is the PR about this Issue: https://github.com/bufferapp/ui/pull/271

@gmzjuliana Hi, Any comment is appreciated :)

**Comment by anafilipadealmeida** [comment]
Thanks for the work here @hijuliancode! 🙂  As we are getting closer to the end of the year and are already in a code freeze mode, we'll revisit this issue and your PR in earlier 2021

**Comment by hamstu** [comment]
Closing as we merged the fix 😄
