### ISSUE TITLE
docs site "show code" broken after removing guides

### ISSUE THREAD

**Issue by gmzjuliana** [bufferapp/ui#287]
this ones on me, I'm sorry! Tyler put this PR together to depreciate the guides section of the site and I approved it but didn't check the component section of the guide: https://github.com/bufferapp/ui/pull/283

We'll need to fix the "show code" link so devs can see the implementation of the components from the docs site

**Comment by hamstu** [comment]
@gomezjuliana oops, it was me that broke this with [this dependabot update](https://github.com/bufferapp/ui/pull/268). (I tested, but also forgot to actually test the code previews, which would have been smart considering... doh! 🙈)

I've just pushed a fix to main and redeployed the docs. That should fix it soon once it's deployed.

**Comment by hamstu** [comment]
Closing as this is fixed by https://github.com/bufferapp/ui/commit/8ba17b86ff7050fa4122cfbcca059246a2ef42a5
